# Generated by Django 4.0.1 on 2022-05-24 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('driving_licence', models.ImageField(upload_to='images/')),
                ('licence_expiry_date', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('experience', models.IntegerField()),
                ('vehicle_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.vehicle')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('accounts.customuser',),
        ),
    ]
